import { photoDesignService as photos } from '../../features/photo-design/service';
import { photoFromDataUrl, photoToDataUrl } from '../../features/photo-design/images';
import { photoMetadata, PHOTO_STYLES, ROOM_TYPES } from '../../features/photo-design/model';
import type { ExecutableTool } from '../registry';
import { uiStore } from '../../state/uiStore';

const string = (description: string) => ({ type: 'string', minLength: 1, description });
const designId = string('ID returned by create_photo_design or list_photo_designs.');
function tool(name: string, title: string, description: string, properties: Record<string, unknown>, required: string[], execute: ExecutableTool['execute'], requiresConfirmation = false): ExecutableTool {
  return { name, title, description, category: 'Workflow', requiresConfirmation, inputSchema: { type: 'object', properties, required, additionalProperties: false }, execute: async (input = {}) => {
    if (!input || typeof input !== 'object' || Array.isArray(input)) throw new Error('Tool input must be an object.');
    for (const key of required) if (input[key] === undefined) throw new Error(`${key} is required.`);
    for (const key of Object.keys(input)) if (!(key in properties)) throw new Error(`Unknown field: ${key}`);
    for (const [key, value] of Object.entries(input)) {
      const schema = properties[key] as { type?: string; enum?: readonly unknown[]; maxLength?: number; minLength?: number; minimum?: number };
      if (schema.type === 'string' && (typeof value !== 'string' || value.length < (schema.minLength || 0) || value.length > (schema.maxLength ?? Infinity))) throw new Error(`Invalid ${key}.`);
      if (schema.type === 'boolean' && typeof value !== 'boolean') throw new Error(`Invalid ${key}.`);
      if (schema.type === 'integer' && (!Number.isInteger(value) || Number(value) < (schema.minimum ?? -Infinity))) throw new Error(`Invalid ${key}.`);
      if (schema.enum && !schema.enum.includes(value)) throw new Error(`Invalid ${key}.`);
    }
    return execute(input);
  } };
}
export const photoDesignTools: Record<string, ExecutableTool> = {
  open_photo_design: tool('open_photo_design', 'Open Photo Design', 'Open the photo design workspace. Uses the signed-in private library when Supabase is configured; otherwise uses this browser.', {}, [], async () => { uiStore.setActiveView('photos'); return { opened: true }; }),
  get_photo_design_capabilities: tool('get_photo_design_capabilities', 'Photo Design Capabilities', 'List room/style choices and OpenAI server configuration. Does not generate an image or incur API charges.', {}, [], async () => ({ roomTypes: ROOM_TYPES, styles: PHOTO_STYLES, server: await photos.config().catch(error => ({ configured: false, error: error.message })), costNotice: 'Generation sends the source photo to OpenAI and incurs API usage charges. Other local operations are free.' })),
  create_photo_design: tool('create_photo_design', 'Upload Room Photo', 'Create a photo design in the active library from a JPEG/PNG/WebP base64 data URL, up to 12 MB. Does not send to OpenAI.', { dataUrl: string('Base64 image data URL; remote URLs are rejected.'), name: string('Name for the photo.') }, ['dataUrl', 'name'], async input => photos.create(photoFromDataUrl(input.dataUrl), input.name)),
  list_photo_designs: tool('list_photo_designs', 'List Photo Designs', 'List photo designs belonging to the active account or local browser and result metadata, without image bytes.', {}, [], async () => ({ designs: await photos.list() })),
  get_photo_design: tool('get_photo_design', 'Get Photo Design', 'Get settings, revision, requests and result IDs without returning image bytes.', { designId }, ['designId'], async input => photoMetadata(await photos.get(input.designId))),
  configure_photo_design: tool('configure_photo_design', 'Configure Photo Design', 'Save room type, style and instructions. Requires the current revision to avoid overwriting another edit.', { designId, revision: { type: 'integer', minimum: 1 }, roomType: { type: 'string', enum: ROOM_TYPES }, styleId: { type: 'string', enum: PHOTO_STYLES.map(s => s.id) }, instruction: { type: 'string', maxLength: 1500 } }, ['designId', 'revision', 'roomType', 'styleId', 'instruction'], async input => photos.configure(input.designId, { roomType: input.roomType, styleId: input.styleId, instruction: input.instruction }, input.revision)),
  prepare_photo_design: tool('prepare_photo_design', 'Prepare Photo Design Brief', 'Save a versioned design brief and request ID. Free; does not generate. Reuses an unfinished identical brief unless newVariation is true.', { designId, newVariation: { type: 'boolean' } }, ['designId'], async input => { if (input.newVariation !== undefined && typeof input.newVariation !== 'boolean') throw new Error('newVariation must be a boolean.'); return { request: await photos.prepare(input.designId, input.newVariation), nextTool: 'generate_photo_design', costNotice: 'Generation is a separate chargeable action requiring confirmation.' }; }),
  generate_photo_design: tool('generate_photo_design', 'Generate Photo Design with OpenAI', 'CHARGEABLE: send this photo and prepared brief to OpenAI to generate one low-quality draft. Requires user cost consent. Returns a job; poll get_photo_design_generation. Never retry using a new request ID after an unknown outcome.', { designId, requestId: string('ID from prepare_photo_design.'), confirmApiCost: { type: 'boolean', const: true, description: 'True only after the user authorizes sending the photo to OpenAI and paying API usage.' } }, ['designId', 'requestId', 'confirmApiCost'], async input => photos.generate(input.designId, input.requestId, input.confirmApiCost), true),
  get_photo_design_generation: tool('get_photo_design_generation', 'Check Photo Generation', 'Check the existing generation and save its completed image to the active library. This never submits another paid generation.', { designId, requestId: string('Existing prepared/generated request ID.') }, ['designId', 'requestId'], async input => photos.refreshGeneration(input.designId, input.requestId)),
  import_photo_design_result: tool('import_photo_design_result', 'Import Photo Concept', 'Attach an externally created concept to a prepared brief. Marks it as imported, not generated by HomeSpace. Aspect ratio must match the source.', { designId, requestId: string('Prepared brief ID.'), dataUrl: string('JPEG/PNG/WebP base64 data URL.') }, ['designId', 'requestId', 'dataUrl'], async input => photos.importResult(input.designId, input.requestId, photoFromDataUrl(input.dataUrl))),
  read_photo_design_asset: tool('read_photo_design_asset', 'Read Photo Design Image', 'Read an explicitly selected source/result as a data URL for agent image handling. Image bytes are omitted from app telemetry.', { designId, assetId: string('Source or result asset ID from get_photo_design.') }, ['designId', 'assetId'], async input => { const asset = await photos.asset(input.designId, input.assetId); return { id: asset.id, width: asset.width, height: asset.height, dataUrl: await photoToDataUrl(asset.blob) }; }),
  favorite_photo_design_result: tool('favorite_photo_design_result', 'Favorite Photo Result', 'Set the favorite flag on a saved result.', { designId, resultId: string('Saved result ID.'), favorite: { type: 'boolean' } }, ['designId', 'resultId', 'favorite'], async input => photos.favorite(input.designId, input.resultId, input.favorite)),
  delete_photo_design: tool('delete_photo_design', 'Delete Photo Design', 'Delete this photo design, its source, briefs and results from the active library and the photo server. Irreversible; refuses while generation is running.', { designId }, ['designId'], async input => photos.remove(input.designId), true),
};
