import assert from 'node:assert/strict';
import { sceneStore } from '../src/state/sceneStore';
import { listSpaceBoundaries, resolveWallPieces } from '../src/geometry/architecture';
import { findFurniturePlacement, auditFurniture } from '../src/geometry/furniturePlacement';
import { architectureTools } from '../src/webmcp/tools/architectureTools';
import { structureTools } from '../src/webmcp/tools/structureTools';
import { createArchitectureGroup, disposeArchitectureGroup } from '../src/canvas/architectureMeshes';

async function run() {
  sceneStore.clearScene();
  const a = sceneStore.createRoom({ name: 'Living', width: 12, depth: 12, position: { x: 0, y: 0, z: 0 } });
  const b = sceneStore.createRoom({ name: 'Dining', width: 12, depth: 12, position: { x: 12, y: 0, z: 0 } });
  const shared = sceneStore.listSpaceBoundaries(a.id).find(w => w.roomId === a.id && w.roomIds.includes(b.id))!;
  assert.ok(shared);
  const baseline = JSON.stringify(sceneStore.getData());
  assert.equal(resolveWallPieces(sceneStore.getData()).filter(p => p.start.x === 6 && p.end.x === 6).length, 1, 'Shared wall rendered once');
  const opened = await architectureTools.set_space_boundary.execute({ wallId: shared.id, kind: 'open' });
  assert.equal(resolveWallPieces(sceneStore.getData()).filter(p => p.start.x === 6 && p.end.x === 6).length, 0);
  assert.equal(sceneStore.getData().rooms.length, 2, 'Zone labels retained');
  sceneStore.undo(); assert.equal(JSON.stringify(sceneStore.getData()), baseline, 'One undo restores edit');
  sceneStore.redo();
  const afterOpen = JSON.parse(JSON.stringify(sceneStore.getData()));
  sceneStore.loadSceneData(afterOpen);
  assert.equal(resolveWallPieces(sceneStore.getData()).filter(p => p.start.x === 6 && p.end.x === 6).length, 0, 'Reload retains opening');
  const chair = sceneStore.addFurniture({ type: 'armchair_accent', roomId: a.id, position: { x: 6, y: 0, z: 0 } });
  assert.equal(chair.position.x, 6, 'Furniture can straddle open zone edge');
  assert.deepEqual(auditFurniture([chair], sceneStore.getData().rooms, [], sceneStore.getData()), []);
  const pieces = resolveWallPieces(sceneStore.getData());
  assert.equal(resolveWallPieces({ ...sceneStore.getData(), doors: sceneStore.getData().doors }), pieces, 'Reuses geometry on non-structural changes');
  const openingId = 'opening' in opened ? opened.opening.id : '';
  await architectureTools.remove_opening.execute({ openingId });
  assert.ok(auditFurniture([chair], sceneStore.getData().rooms, []).length);
  sceneStore.deleteObject(chair.id);
  const door = await structureTools.place_door.execute({ roomId: a.id, wallId: shared.id, offset: 4, width: 3, height: 7, hinge: 'right', swing: 'outward' });
  assert.equal(Math.abs(door.rotation), 90);
  const current = sceneStore.getData();
  const lintel = resolveWallPieces(current).find(p => p.start.x === 6 && p.end.x === 6 && p.base === 7);
  assert.ok(lintel, 'Door has overhead masonry');
  const unchanged = JSON.stringify(current);
  assert.throws(() => sceneStore.placeDoor({ roomId: a.id, wallId: shared.id, offset: 5, width: 3 }), /already contains/);
  assert.throws(() => sceneStore.setSpaceBoundary({ wallId: shared.id, kind: 'open', offset: -1 }), /fit/);
  assert.equal(JSON.stringify(sceneStore.getData()), unchanged, 'Rejected edits do not change scene');
  await architectureTools.update_door.execute({ doorId: door.doorId, offset: 1, hinge: 'left', swing: 'inward' });
  assert.equal(sceneStore.getData().doors[0].offset, 1);
  const group = createArchitectureGroup(sceneStore.getData(), true);
  assert.ok(group.children.length > 0); disposeArchitectureGroup(group);
  const far = { ...chair, position: { x: 100, y: 0, z: 100 }, roomId: undefined };
  assert.equal(findFurniturePlacement(far, current.rooms, [], [], false, sceneStore.getData()), null);
  const boundaries = listSpaceBoundaries(sceneStore.getData());
  assert.equal(boundaries, listSpaceBoundaries(sceneStore.getData()), 'Boundary topology cached');
  assert.equal(sceneStore.rotateObject(door.doorId, 45), false, 'Managed doors cannot detach from their wall');
  const oldDoorX = sceneStore.getData().doors[0].position.x;
  sceneStore.moveRoom(a.id, { x: -20, y: 0, z: 0 });
  assert.equal(sceneStore.getData().doors[0].position.x, oldDoorX - 20, 'Door follows room move');
  sceneStore.undo();
  sceneStore.setTransformLock(b.id, true);
  assert.throws(() => sceneStore.updateDoor(door.doorId, { width: 4 }), /Unlock/);
  sceneStore.setTransformLock(b.id, false);
  sceneStore.removeOpening(door.doorId);
  sceneStore.setSpaceBoundary({ wallId: shared.id, kind: 'open', offset: 3, width: 6 });
  const partial = resolveWallPieces(sceneStore.getData()).filter(p => p.start.x === 6 && p.end.x === 6);
  assert.equal(partial.length, 2, 'Partial connection retains both wall ends');
  assert.equal(partial.reduce((sum, p) => sum + Math.hypot(p.end.x - p.start.x, p.end.z - p.start.z), 0), 6);
  assert.ok(auditFurniture([{ ...chair, position: { x: 6, y: 0, z: 4.8 } }], sceneStore.getData().rooms, [], sceneStore.getData()).length, 'Furniture cannot cross remaining solid wall');
  sceneStore.clearScene();
  const polygon = [{ x: 0, y: 0 }, { x: 12, y: 0 }, { x: 12, y: 12 }, { x: 0, y: 12 }];
  sceneStore.setFloorPlan({ id: 'import-test', name: 'Import', scale: 1, unit: 'feet', openings: [],
    rooms: [{ id: 'import-room', name: 'Imported room', role: 'living', width: 12, depth: 12, center: { x: 6, y: 6 }, polygon }],
    walls: polygon.map((p, i) => ({ id: `import-wall-${i}`, start: p, end: polygon[(i + 1) % 4], roomId: 'import-room', thickness: 0.5, isExterior: true })),
    bounds: { minX: 0, minY: 0, maxX: 12, maxY: 12, widthFeet: 12, depthFeet: 12 } });
  assert.equal(sceneStore.listSpaceBoundaries().length, 4, 'Imported plans use explicit walls, not zone edges');
  sceneStore.placeDoor({ roomId: 'import-room', wallId: 'import-wall-0', offset: 4 });
  sceneStore.undo(); assert.equal(sceneStore.getData().floorPlan?.id, 'import-test', 'Undo preserves imported source');
  sceneStore.redo();
  sceneStore.loadSceneData(JSON.parse(JSON.stringify(sceneStore.getData())));
  assert.equal(sceneStore.getData().floorPlan?.id, 'import-test', 'Reload preserves imported source');
  console.log('Architecture: shared walls, open zones, doors, validation, WebMCP, caching, rendering, save/reload and Undo passed.');
}
run().catch(e => { console.error(e); process.exitCode = 1; });
